# Generated by Django 5.2.8 on 2025-11-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.URLField(blank=True, null=True, verbose_name="Аватар"),
        ),
    ]
