# Generated by Django 5.2.8 on 2025-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
    ]
